### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by NikkoJaca** [NikkoJaca/flaremob-sagip-webapp#1]
Login 404 handler defaults to "alisto"

*Madaming myapp.js di ko alam kung saan dito HAHAHA

See https://flaremob-b55d8.firebaseapp.com/

**Comment by michael-cembrano** [comment]
ansa firebasejsquerys/myapp.js ung laman kso ung 404 handler wala pa tayo ih

**Comment by michael-cembrano** [comment]
![image](https://user-images.githubusercontent.com/30582112/48975937-c8012600-f0b7-11e8-8cb0-7c3f5968ff3d.png)
ano to??

**Comment by NikkoJaca** [comment]
hmm medyo may issue yung sa web hosting ng firebase, feeling ko di niya  tinatanggap ung relative path

**Comment by NikkoJaca** [comment]
per tab ba talaga yung login?

**Comment by NikkoJaca** [comment]
epic nung registration menu natin for walk in donations lang talaga un boisss? everytime i login gamit nung registration module from the login ang bagsak ko sa pledging XD
